<h1>A 403 error occured</h1>
<p>
    <?php if ($error == 'error-route-unauthorized') : ?>
        Identity (with roles <?php echo implode(',', $identity->getRoles());?>) is not authorized to access <?php echo $route;?>.
    <?php elseif ($error == 'error-controller-unauthorized') : ?>
        Identity (with roles <?php echo implode(',', $identity->getRoles());?>) is not authorized to access <?php echo $controller;?>
        <?php if ($action) : ?>
            ::<?php echo $action;?>Action()
        <?php endif;?>
        .
    <?php elseif ($error == 'error-rbac') : ?>
        RBAC error<br/>
        <?php if ($this->message) : ?>
            <?php echo $this->message;?>
        <?php endif;?>
    <?php endif;?>
</p>
